apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: app
spec:
  ports:
    - name: simple
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    app: daemonset
  type: NodePort