apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simple-deamonset
  namespace: app
spec:
  selector:
    matchLabels:
      app: daemonset
  template:
    metadata:
      labels:
        app: daemonset
    spec:
      containers:
      - name: simple-web
        image: ne0kk/simple-web:latest