         
name: Build Docker Image CI

on:
  push:
    # branches:
    #   - dev
    # paths:
    #   - 'app/source/**'
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: actions/checkout@v4

      - name: Docker Hub enter
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKER_HUB }}
          password: ${{ secrets.TOKEN_DOCKER_HUB }}

      - name: Build Docker Hub Registry
        env:
           IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
           IMAGE_TAG1: github.ref_name || 'latest'
           IMAGE_TAG2: github.ref_name
        run: |
          echo $IMAGE_TAG
          echo $IMAGE_TAG1
          echo $IMAGE_TAG2
          docker build . --file app/source/Dockerfile --tag simple-web:$IMAGE_TAG
          docker tag simple-web:$IMAGE_TAG ${{ secrets.USER_DOCKER_HUB }}/simple-web:$IMAGE_TAG
          docker push ${{ secrets.USER_DOCKER_HUB }}/simple-web:$IMAGE_TAG