name: Deploy to YC Kubernetes

on:
  push:
    # branches:
    #   - main
    # paths:
    #   - 'app/source/**'
    #   - 'app/kube_deploy/**'
    tags:
      - v*


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #1: Clone repo
      - name: Checkout code
        uses: actions/checkout@v4

      #2: Install Yandex CLI
      - name: Install Yandex Cloud CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "${HOME}/yandex-cloud/bin" >> $GITHUB_PATH

      #3: Enter в Yandex Cloud
      - name: Authenticate in Yandex Cloud
        env:
          YC_SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
        run: |
          echo "${YC_SERVICE_ACCOUNT_KEY}" > yc-sa-key.json
          yc config set service-account-key yc-sa-key.json
          yc config set cloud-id "${YC_CLOUD_ID}"
          yc config set folder-id "${YC_FOLDER_ID}"

      #4: Install kubectl
      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      #5:  Connect Kubernetes
      - name: Configure kubectl
        env:
          YC_SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          YC_CLUSTER_NAME: ${{ secrets.YC_CLUSTER_NAME }}
        run: |
          yc managed-kubernetes cluster get-credentials --name "${YC_CLUSTER_NAME}" --external
          kubectl get nodes

      # Шаг 6: Deploy APP
      - name: Deploy to Kubernetes
        env:
           IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
        run: |
          kubectl config view
          kubectl get nodes
          kubectl get pods --all-namespaces
          kubectl set image deployment/simple-deploynent simple-web=${{ secrets.USER_DOCKER_HUB }}/simple-web:$IMAGE_TAG -n app
          kubectl rollout status deployment/simple-deploynent -n app
          kubectl get pods --all-namespaces
        #  kubectl delete -f app/kube_deploy/APP-DaemonSet.yml -f app/kube_deploy/APP-service.yml
        #  kubectl apply -f app/kube_deploy/APP-DaemonSet.yml -f app/kube_deploy/APP-service.yml
        # kubectl create deployment nginx --image=${{ secrets.USER_DOCKER_HUB }}/simple-web:$IMAGE_TAG
        # kubectl set image deployment/simple-deploynent simple-web=ne0kk/simple-web:latest -n app
        # kubectl rollout status deployment/simple-deploynent -n app

